
PCLOUD_API_KEY = "wiaJJZfKQB7ZFJGbF2LjLo0nFysSdWCN0mklLXYV"
PCLOUD_PATH = "/Apps/LLMChat"

DROPBOX_API_KEY = "sl.Bk06nWfDxVu6Yx1961Pm_CQRPEE5xHiWff9Y9K_4vYtPghmLqWsyROtECGXrmzMbirlL6acFjajOR7bZDzGMs8R0oOoKuEozbFiAQD2IBT8j-W5pLgigWBl5LEe1t4gC1dMxKcSmHdyDE88"
DROPBOX_FOLDER = "/LLMChat"