
PCLOUD_API_KEY = "wiaJJZfKQB7ZFJGbF2LjLo0nFysSdWCN0mklLXYV"
PCLOUD_PATH = "/Apps/LLMChat"

DROPBOX_API_KEY = "sl.BlQhd0JSb29rv0Tm2ssQNC5dxuDD_l4VlosmzqfZ4z2_dcqgL71DvSQktRhz_9etjLxn7LPwW9CLEqh7h2mcnNuiv-ZVrK9fqz_EZ8zvfEE0YenuCxVkBOTfKKfFmwJGmY9C9DU2l0nBGxY"
DROPBOX_FOLDER = "/LLMChat"
