
PCLOUD_API_KEY = "wiaJJZfKQB7ZFJGbF2LjLo0nFysSdWCN0mklLXYV"
PCLOUD_PATH = "/Apps/LLMChat"

DROPBOX_API_KEY = "sl.BkxHBGTZSDDid4DSzHWe-umimhFIWyaoi8dlO1EbiH8VJYHBMu3KKUHMox47jWQZ5X7jKuUvn_O0zSwWDgPDfW2Zgl93wVzAhnI0FqWcI_K4tPoUYeXR0Py5odFC7oi00PRqeDEEF87kEas"
DROPBOX_FOLDER = "/LLMChat"